[project]
authors = [
  {name = "James Demetris"},
]
dynamic = ["version", "description", "license"]
name = "slots_sort"
requires-python = ">= 3.8"

[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools >= 69.0.0",
]
